name: 'SignArchives'
description: 'Signs the archives'
author: 'Marcus Tillmanns'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'green'

# Define your inputs here.
inputs:
  macos:
    description: 'Path to macos archive'
    required: false
    default: ''
  win-x64:
    description: 'Path to Windows x64 archive'
    required: false
    default: ''
  win-arm64:
    description: 'Path to Windows arm64 archive'
    required: false
    default: ''
  jenkins-url:
    description: Url to jenkins
    required: true
    default: ''
  jenkins-user:
    description: 'Username for jenkins'
    required: true
    default: ''
  jenkins-token:
    description: 'API Token for jenkins'
    required: true
    default: ''

# Define your outputs here.
outputs:
  macos:
    description: 'Path to signed archive for macos'
  win-x64:
    description: 'Path to signed archive for windows x64'
  win-arm64:
    description: 'Path to signed archive for windows arm64'

runs:
  using: node20
  main: dist/index.js
